In [1]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [2]:
link ="https://drive.google.com/open?id=1Zd76wx4SMpRWJOsbYZ2TaS5toIC1ZLfc"

In [3]:
fluff, id = link.split('=')
print (id)

1Zd76wx4SMpRWJOsbYZ2TaS5toIC1ZLfc


In [4]:
import pandas as pd
downloaded = drive.CreateFile({'id':id}) 
#downloaded.GetContentFile('Segmented.zip')
#downloaded.GetContentFile('Filename')  
#df = pd.read_csv('Filename.csv')

In [5]:
downloaded.GetContentFile('Data_Easy_Images.zip')

In [6]:
from zipfile import ZipFile
with ZipFile('/content/Data_Easy_Images.zip', 'r') as zipObj:
   zipObj.extractall()

In [7]:
import os
import glob
import matplotlib.pyplot as plt
import cv2
easy_img_dir ="/content/Data_Easy_Images"
easy_data_path =os.path.join(easy_img_dir,'*g')
easy_files = glob.glob(easy_data_path)
# print(train_files[0])
# a=cv2.imread(train_files[56])


In [8]:
link1="https://drive.google.com/open?id=1U9Yf5A-OEb7uLMtxMFdpfTOW-WhpcrCH"

In [9]:
fluff, id1 = link1.split('=')
print (id1)

1U9Yf5A-OEb7uLMtxMFdpfTOW-WhpcrCH


In [10]:
import pandas as pd
downloaded = drive.CreateFile({'id':id1})
downloaded.GetContentFile('easy.csv')
df=pd.read_csv("easy.csv",header=None)



In [11]:
easy_label=df.values
easy_label.shape

(7413, 1)

In [12]:
easy_images_ordered_name=[]
for i in range(0,len(easy_files)):
  x=easy_files[i].split("/")
  y=x[len(x)-1]
  easy_images_ordered_name.append(y)


In [13]:
easy_correct_label=[]
for i in range(0,len(easy_files)):
  x = easy_images_ordered_name[i].split(".")
  y = int(x[1])-1
  easy_correct_label.append(easy_label[y])

In [14]:
link2 = "https://drive.google.com/open?id=15arnU5pd8ns_nV7ObG60QrR18oFoJ1Gr"

In [15]:
fluff, id2 = link2.split('=')
print (id2)

15arnU5pd8ns_nV7ObG60QrR18oFoJ1Gr


In [16]:
downloaded = drive.CreateFile({'id':id2}) 
downloaded.GetContentFile('Data_Hard_Images.zip')

In [17]:
from zipfile import ZipFile
with ZipFile('/content/Data_Hard_Images.zip', 'r') as zipObj:
   zipObj.extractall()

In [18]:
import os
import glob
import matplotlib.pyplot as plt
import cv2
hard_img_dir ="/content/Data_Hard_Images"
hard_data_path =os.path.join(hard_img_dir,'*g')
hard_files = glob.glob(hard_data_path)

In [19]:
hard_images_ordered_name=[]
for i in range(0,len(hard_files)):
  x=hard_files[i].split("/")
  y=x[len(x)-1]
  hard_images_ordered_name.append(y)

In [20]:
link3 = "https://drive.google.com/open?id=1qOqs6gyEiPne5b4aLlhGNGm5nZUzlGzw"

In [21]:
fluff, id3 = link3.split('=')
print (id3)

1qOqs6gyEiPne5b4aLlhGNGm5nZUzlGzw


In [22]:
import pandas as pd
downloaded = drive.CreateFile({'id':id3})
downloaded.GetContentFile('hard.csv')
df1=pd.read_csv("hard.csv",header=None)


In [23]:
import numpy as np
hard_label=df1.values
hard_label=np.array(hard_label)

In [24]:
hard_label[4]

array([1])

In [25]:
for i in range(0,len(hard_label)):
  if hard_label[i]==0:
    hard_label[i]=1
  else:
    hard_label[i]=0


In [26]:
hard_label[840]

array([1])

In [27]:
hard_label[4]

array([0])

In [28]:
hard_correct_label=[]
for i in range(0,len(hard_files)):
  x = hard_images_ordered_name[i].split(".")
  y = int(x[1])-1
  hard_correct_label.append(hard_label[y])

In [29]:
for i in range(0,len(hard_files)):
  easy_correct_label.append(hard_correct_label[i])

In [30]:
easy_correct_label[7414]

array([0])

In [31]:
for i in range(0,len(hard_files)):
  easy_files.append(hard_files[i])

In [32]:
easy_files[7414]

'/content/Data_Hard_Images/Rest.00369.jpg'

In [33]:
train_correct_label=easy_correct_label

In [34]:
train_files=easy_files

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from keras.layers import Input,Dense,Conv2D, MaxPooling2D, UpSampling2D
from keras.layers import Flatten, Reshape,Dropout
from keras.models import Model, Sequential 
from keras import regularizers
from keras.utils import to_categorical
from keras.layers.normalization import BatchNormalization
from numba import jit,cuda
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import tensorflow as tf
import pickle
import h5py

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [37]:
train_correct_label=to_categorical(train_correct_label)

In [38]:
train_correct_label[9]

array([1., 0.], dtype=float32)

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.layers import Input,Dense,Conv2D, MaxPooling2D, UpSampling2D
from tensorflow.keras.layers import Flatten, Reshape,Dropout
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras import regularizers
from tensorflow.keras.utils import to_categorical
from keras.layers.normalization import BatchNormalization
from numba import jit,cuda
from imblearn.over_sampling import SMOTE

In [40]:
from skimage.transform import resize
train_images_pixels=[]
for i in range(0, len(train_files)):
  image=cv2.imread(train_files[i])
  image_resized= resize(image,(56,128,3))
  train_images_pixels.append(image_resized)

In [41]:
train_images_pixels=np.array(train_images_pixels)
#train_images_pixels = train_images_pixels.reshape((len(train_images_pixels),56,128,3))

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
        train_images_pixels, train_correct_label, train_size=0.75, test_size=0.25, random_state=42, shuffle=True)

In [44]:
X_train_1, X_validate, y_train_1, y_validate = train_test_split(
        X_train, y_train, train_size=0.80, test_size=0.20, random_state=42, shuffle=True)

In [45]:
X_train_1=X_train_1.reshape((len(X_train_1),56,128,3))
X_validate=X_validate.reshape((len(X_validate),56,128,3))
X_test=X_test.reshape((len(X_test),56,128,3))

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(
        train_images_pixels, train_correct_label, train_size=0.75, test_size=0.25, random_state=42, shuffle=True)

In [ ]:
X_train_11, X_validate1, y_train_11, y_validate1 = train_test_split(
        X_train1, y_train1, train_size=0.80, test_size=0.20, random_state=42, shuffle=True)

In [46]:
from keras.regularizers import l2
from keras.optimizers import SGD
def build_model_final(train_images,train_labels1,X_valid_images,y_valid,batch_size=10,epochs=12,verbose=1):
    model=Sequential()
    model.add(Conv2D(32,(7,3),strides=(1, 1),activation='relu',kernel_regularizer=l2(0.000005),input_shape=(56,128,3)))
    #model.add(BatchNormalization())
    model.add(MaxPooling2D((2,2)))
    model.add(Conv2D(64,(6,4),strides=(1, 1),activation='relu',kernel_regularizer=l2(0.000005)))
    #model.add(BatchNormalization())
    model.add(MaxPooling2D((2,2)))
    #model.add(Dropout(0.25))
    #model.add(Conv2D(64,(3,3),strides=(1, 1),activation='relu'))
    #model.add(BatchNormalization())
    #model.add(Dropout(0.25))
    #model.add(Conv2D(128,(3,3),strides=(1, 1),activation='relu'))
    #model.add(BatchNormalization())
    #model.add(MaxPooling2D((2,2)))
    #model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(50,activation='relu',kernel_regularizer=l2(0.000005)))
    #model.add(BatchNormalization())
    #model.add(Dropout(0.5))
    model.add(Dense(2,activation='relu',kernel_regularizer=l2(0.000005)))
    #model.add(BatchNormalization())
    #model.add(Dropout(0.5))
    model.add(Dense(2,activation='softmax'))
    learning_rate = 0.01
    momentum = 0.9
    sgd = SGD(lr=learning_rate,momentum = momentum,nesterov=False)
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',patience=3)
    hist=model.fit(train_images,train_labels1,batch_size,epochs,verbose,callbacks=[callback],validation_data=(X_valid_images,y_valid))
    return model,hist

In [47]:
model,history = build_model_final(X_train_1,y_train_1,X_validate,y_validate)

Epoch 1/12
501/501 [==============================] - 12s 24ms/step - loss: 0.4363 - accuracy: 0.8078 - val_loss: 0.3005 - val_accuracy: 0.8761
Epoch 2/12
501/501 [==============================] - 12s 23ms/step - loss: 0.2968 - accuracy: 0.8870 - val_loss: 0.2781 - val_accuracy: 0.8833
Epoch 3/12
501/501 [==============================] - 12s 23ms/step - loss: 0.2523 - accuracy: 0.8976 - val_loss: 0.2484 - val_accuracy: 0.9169
Epoch 4/12
501/501 [==============================] - 12s 23ms/step - loss: 0.2265 - accuracy: 0.9106 - val_loss: 0.2518 - val_accuracy: 0.9065
Epoch 5/12
501/501 [==============================] - 12s 24ms/step - loss: 0.2053 - accuracy: 0.9234 - val_loss: 0.2134 - val_accuracy: 0.9209
Epoch 6/12
501/501 [==============================] - 11s 22ms/step - loss: 0.1884 - accuracy: 0.9312 - val_loss: 0.2292 - val_accuracy: 0.9097
Epoch 7/12
501/501 [==============================] - 11s 22ms/step - loss: 0.1758 - accuracy: 0.9368 - val_loss: 0.2122 - val_accuracy:

In [48]:
test_loss,test_acc=model.evaluate(X_test,y_test)
print('test_acc:',test_acc)

66/66 [==============================] - 1s 10ms/step - loss: 0.2058 - accuracy: 0.9213
test_acc: 0.9213051795959473


In [49]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

In [52]:
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

In [51]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 50, 126, 32)       2048      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 25, 63, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 20, 60, 64)        49216     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 30, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 19200)             0         
_________________________________________________________________
dense (Dense)                (None, 50)                960050    
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 1